version: "3.2"
services:
  mediawiki:
    build: .
    restart: always
    links:
      - database
    volumes:
      - "./config/secret.php:/var/www/html/secret.php"
      - "./config/LocalSettings.php:/var/www/html/LocalSettings.php"
      # Custom Extension for Hanyang Wiki
      # Please Remove Comment below for Development
      #- "../hy-wiki-skin:/var/www/html/skins/hy-wiki-skin"
    ports:
      - "80:80"
  database:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wikidb
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - "./.mariadb:/var/lib/mysql"
  parsoid:
    image: thenets/parsoid:0.10.0
    ports:
      - 8081:8000
    environment:
      - PARSOID_DOMAIN_mediawiki=http://mediawiki/api.php
