version: "3.2"
services:
  http:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./http:/etc/nginx/conf.d:ro # EB deploy files to /var/app/current. you have to modify it to $PWD in Dockerrun.aws.json
      - files:/usr/src
    links:
      - mediawiki
  mediawiki:
    image: hywiki/mediawiki:v0
    volumes:
      - ./config:/ct:ro # EB deploy files to /var/app/current. you have to modify it to $PWD in Dockerrun.aws.json
      - files:/usr/src
    links:
      - memcached
  parsoid:
    image: thenets/parsoid:0.10.0
    ports:
      - 8081:8000
    environment:
      - PARSOID_DOMAIN_mediawiki=http://http/api.php
  memcached:
    image: memcached:1-alpine

volumes:
  files:
  database:
