name: Deploying Hanyang Wiki to Elastic Beanstalk

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Upload Docker Image to ECR and Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION_NAME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hy-wiki/mediawiki
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
        
      - name: Generate deployment package
        run: zip -r deploy.zip . -x *.git*

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_KEY }}
          region: ${{ secrets.AWS_EB_REGION_NAME }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
          deployment_package: deploy.zip
          version_label: ${{ github.sha }}
          use_existing_version_if_available: true
          wait_for_deployment: false
