name: Hanyang Wiki AWS Elastic Beanstalk Deploy Production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v9
        with:
          aws_access_key: ${{ secrets.AWS_BEANSTALK_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_BEANSTALK_SECRET_KEY }}
          region: ${{ secrets.AWS_BEANSTALK_REGION_NAME }}
          application_name: ${{ secrets.AWS_BEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_BEANSTALK_ENVIRONMENT_NAME }}
